# -*- coding: utf-8 -*-
"""TitanicSurvived.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WJsZMd2iGx5dYkvasOqlaE7UhPQoBrLa
"""

import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

df =  pd.read_csv("/content/drive/My Drive/titanic/train.csv")

df.head()

df.describe()

import matplotlib.pyplot as plt

df.isnull().sum()

df["Age"].fillna(df["Age"].mean(),inplace=True)
df["Embarked"].fillna(df["Embarked"].mode, inplace= True)

df[0:10]

df["Sex"] = df["Sex"].replace("male",0)
df["Sex"] = df["Sex"].replace("female",1)

feat = ["Pclass","Sex","Age","SibSp","Parch","Fare"]
target = ["Survived"]

x = []
x = df[feat]
y = df[target]



from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.20)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

from sklearn import svm

clf=svm.LinearSVC()
clf.fit(x_train,y_train)
print(clf)

print(clf.score(x_test,y_test))

from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0).fit(x_train,y_train)

print(clf.score(x_test,y_test))

from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0)
clf.fit(x_train,y_train)
print(clf.score(x_test,y_test))

from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(max_depth=10, random_state=0)
clf.fit(x_train,y_train)
print(clf.score(x_test,y_test))



test=  pd.read_csv("/content/drive/My Drive/titanic/test.csv")

test_df = test[feat]
test_df["Sex"] = test_df["Sex"].replace("male",0)
test_df["Sex"] = test_df["Sex"].replace("female",1)

test_df.isnull().sum()

test_df["Age"].fillna(test_df["Age"].mean(),inplace=True)

test_df["Fare"].fillna(test_df["Fare"].mean(),inplace=True)

x = clf.predict(test_df)
x.shape

res = pd.DataFrame({'PassengerId':test['PassengerId'],'Survived':x})

res.head()
res.to_csv("/content/drive/My Drive/titanic/res.csv", index = False)

res.head()

